export const CREAR_PRODUCTO = "CREAR_PRODUCTO";
export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const EDITAR_PRODUCTO = "EDITAR_PRODUCTO";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const ERROR_PRODUCTOS = "ERROR_PRODUCTOS";

export const CREAR_PEDIDO = "CREAR_PEDIDO";
export const OBTENER_PEDIDOS = "OBTENER_PEDIDOS";
export const OBTENER_PEDIDO = "OBTENER_PEDIDO";
export const ERROR_PEDIDOS = "ERROR_PEDIDOS";
export const AGREGAR_PRODUCTOS_PEDIDO = "AGREGAR_PRODUCTOS_PEDIDO";

export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_CLIENTE = "OBTENER_CLIENTE";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const AUTH_ERROR = "AUTH_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
